// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: proto/llm.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LLMRouterClient is the client API for LLMRouter service.
type LLMRouterClient interface {
	RoutePrompt(ctx context.Context, in *RouteRequest, opts ...grpc.CallOption) (*RouteResponse, error)
	StreamPrompt(ctx context.Context, in *RouteRequest, opts ...grpc.CallOption) (LLMRouter_StreamPromptClient, error)
}

type llmRouterClient struct {
	cc grpc.ClientConnInterface
}

func NewLLMRouterClient(cc grpc.ClientConnInterface) LLMRouterClient {
	return &llmRouterClient{cc}
}

func (c *llmRouterClient) RoutePrompt(ctx context.Context, in *RouteRequest, opts ...grpc.CallOption) (*RouteResponse, error) {
	out := new(RouteResponse)
	err := c.cc.Invoke(ctx, "/maars.llm.LLMRouter/RoutePrompt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *llmRouterClient) StreamPrompt(ctx context.Context, in *RouteRequest, opts ...grpc.CallOption) (LLMRouter_StreamPromptClient, error) {
	stream, err := c.cc.NewStream(ctx, &LLMRouter_ServiceDesc.Streams[0], "/maars.llm.LLMRouter/StreamPrompt", opts...)
	if err != nil {
		return nil, err
	}
	x := &llmRouterStreamPromptClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LLMRouter_StreamPromptClient interface {
	Recv() (*StreamResponse, error)
	grpc.ClientStream
}

type llmRouterStreamPromptClient struct {
	grpc.ClientStream
}

func (x *llmRouterStreamPromptClient) Recv() (*StreamResponse, error) {
	m := new(StreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// LLMRouterServer is the server API for LLMRouter service.
// All implementations must embed UnimplementedLLMRouterServer
// for forward compatibility
type LLMRouterServer interface {
	RoutePrompt(context.Context, *RouteRequest) (*RouteResponse, error)
	StreamPrompt(*RouteRequest, LLMRouter_StreamPromptServer) error
	mustEmbedUnimplementedLLMRouterServer()
}

// UnimplementedLLMRouterServer must be embedded to have forward compatible implementations.
type UnimplementedLLMRouterServer struct {
}

func (UnimplementedLLMRouterServer) RoutePrompt(context.Context, *RouteRequest) (*RouteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RoutePrompt not implemented")
}
func (UnimplementedLLMRouterServer) StreamPrompt(*RouteRequest, LLMRouter_StreamPromptServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamPrompt not implemented")
}
func (UnimplementedLLMRouterServer) mustEmbedUnimplementedLLMRouterServer() {}

// UnsafeLLMRouterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LLMRouterServer will
// result in compilation errors.
type UnsafeLLMRouterServer interface {
	mustEmbedUnimplementedLLMRouterServer()
}

func RegisterLLMRouterServer(s grpc.ServiceRegistrar, srv LLMRouterServer) {
	s.RegisterService(&LLMRouter_ServiceDesc, srv)
}

func _LLMRouter_RoutePrompt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMRouterServer).RoutePrompt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/maars.llm.LLMRouter/RoutePrompt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMRouterServer).RoutePrompt(ctx, req.(*RouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMRouter_StreamPrompt_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RouteRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LLMRouterServer).StreamPrompt(m, &llmRouterStreamPromptServer{stream})
}

type LLMRouter_StreamPromptServer interface {
	Send(*StreamResponse) error
	grpc.ServerStream
}

type llmRouterStreamPromptServer struct {
	grpc.ServerStream
}

func (x *llmRouterStreamPromptServer) Send(m *StreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

// LLMRouter_ServiceDesc is the grpc.ServiceDesc for LLMRouter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LLMRouter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "maars.llm.LLMRouter",
	HandlerType: (*LLMRouterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RoutePrompt",
			Handler:    _LLMRouter_RoutePrompt_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamPrompt",
			Handler:       _LLMRouter_StreamPrompt_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/llm.proto",
}

// Made with Bob
